portfolio/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import HomePageView, ProfileView, ProfileEditView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('profile', login_required(ProfileView.as_view()), name='profile'),
    path('profile/edit', login_required(ProfileEditView.as_view()), name='profile_edit'),
]

project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('portfolio.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/models.py
from django.contrib.gis.db import models as gis
from django.db import models
from django.db.models.signals import post_save, pre_save, pre_delete
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField
from users.models import CustomUser
import os

class BaseModel(models.Model):
    """
    Abstract Model to be inherited by other model in profile
    """

    created_at = models.DateTimeField(null=True, blank=True, auto_now_add=True)
    updated_at = models.DateTimeField(null=True, blank=True, auto_now=True)

    class Meta:
        abstract = True

def user_photo_directory(instance, filename):
    """
    Callback for Profile photo upload
    :param instance: saved object (Profile)
    :param filename: uploaded photo_name
    :return: path of uploaded file
    """
    filename, ext = os.path.splitext(filename)
    return '{}/photo{}'.format(instance.user.username, ext)

class Expertise(BaseModel):
    """
    Model for available expertise, e.g Python, Django, HTML
    """
    name = models.CharField(max_length=15, blank=False, null=False)

    def __unicode__(self):
        return '{}'.format(self.name)

    def __str__(self):
        return self.__unicode__()

    class Meta:
        ordering = ('name',)

class Profile(BaseModel):
    """
    Model for User Profile, has OnetoOne relationship with CustomUser
    """

    user = models.OneToOneField(CustomUser, null=False, default=1, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to=user_photo_directory, null=True, blank=True)
    first_name = models.CharField(max_length=20, null=False, blank=False, default='')
    last_name = models.CharField(max_length=20, null=False, blank=False, default='')
    address = models.CharField(max_length=100, default='', null=False, blank=True)
    phone = PhoneNumberField(max_length=15, null=False, blank=True, default='')
    expertise = models.ManyToManyField(Expertise)
    location = gis.PointField(null=True, default=None, blank=True)

    def __unicode__(self):
        return '{} - {} - {}'.format(self.user.username, self.user.first_name + ' ' + self.user.last_name, self.phone)

    def __str__(self):
        return self.__unicode__()

    class Meta:
        ordering = ('-id',)

@receiver(post_save, sender=Profile)
def update_user_name(sender, instance, **kwargs):
    """
    Change User first_name and last_name when updating Profile
    first_name and last_name
    :param sender: Profile
    :param instance: Profile instance (saved Profile object)
    """
    if not instance.first_name == '':
        instance.user.first_name = instance.first_name
    if not instance.last_name == '':
        instance.user.last_name = instance.last_name
    instance.user.save()

@receiver(pre_delete, sender=Profile)
def auto_delete_photo_on_delete(sender, instance, **kwargs):
    """
    Deletes old photo from filesystem when
    Profile object is deleted.
    """

    if not instance.pk:
        return False

    try:
        photo = sender.objects.get(pk=instance.pk).photo
    except sender.DoesNotExist:
        return False

    if bool(photo) == True:
        if os.path.isfile(photo.path):
            os.remove(photo.path)

@receiver(pre_save, sender=Profile)
def auto_delete_photo_on_update(sender, instance, **kwargs):
    """
    Deletes old photo from filesystem when
    Profile object is updated with new photo.
    """

    if not instance.pk:
        return False

    try:
        old_photo = sender.objects.get(pk=instance.pk).photo
    except sender.DoesNotExist:
        return False

    new_photo = instance.photo
    if not old_photo == new_photo and bool(old_photo) == True:
        if os.path.isfile(old_photo.path):
            os.remove(old_photo.path)

portfolio/forms.py
from django import forms
from django.contrib.gis import forms as gis_forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column
from phonenumber_field.formfields import PhoneNumberField
from .models import Profile, Expertise

class ProfileForm(forms.ModelForm):
    """
    Form to edit Profile
    """

    # For loction field, we will use OpenStreetMap Widget
    location = gis_forms.PointField(required=False, widget=gis_forms.OSMWidget(
            attrs={
                'default_lat': -7.7129,
                'default_lon': 110.0093,
                'default_zoom': 11,
                'map_width': 1050,
            }
        ),
    )
    # Expertise can have multiple value, so we will use Multiple ModelMultipleChoiceField
    expertise = forms.ModelMultipleChoiceField(required=False, queryset=Expertise.objects.all(),
                                               widget=forms.SelectMultiple(attrs={'style': 'width:100%;'}))

    phone = PhoneNumberField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.attrs = {'id': 'profile-form'} #give id to form
        self.helper.layout = Layout(
            'photo',
            Row(
                Column(
                    Row(
                        Column('first_name', css_class='col-12 col-sm-4 input-sm '),
                        Column('last_name', css_class='col-12 col-sm-4 input-sm'),
                        Column('phone', css_class='col-12 col-sm-4 input-sm '),
                        css_class='row'
                    ),
                    css_class='col-md-12'
                ),
                css_class='form-row row'
            ),
            Row(
                Column(
                    Row(
                        Column('expertise', css_class='col-12 col-sm-4 input-sm'),
                        Column('address', css_class='col-12 col-sm-8 input-sm'),
                        css_class='row'
                    ),
                    css_class='col-md-12'
                ),
                css_class='form-row row'
            ),
            'location',
            Submit('submit', 'Save')
        )

    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ('user',)

portfolio/views.py
from django.views.generic import DetailView, ListView, TemplateView, UpdateView
from django.forms.models import model_to_dict
from portfolio.models import Profile
from portfolio.forms import ProfileForm
from django.urls import reverse_lazy

class HomePageView(ListView):
    """
    Views for Home and User List, which shows other user's profile in full map.
    """
    template_name = 'portfolio/profile_list.html'
    model = Profile
    queryset = Profile.objects.all().prefetch_related('expertise','user')
    extra_context = dict()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu_page'] = 'home' # variable to indicate which page the user is in

        return context


class ProfileView(DetailView):
    """
    Views for User Profile.
    """
    template_name = 'portfolio/profile.html'
    model = Profile
    extra_context = dict()

    def get_object(self, queryset=None):
        # get profile if profile exists, create profile if profile does not exist
        obj, created = self.model.objects.get_or_create(user=self.request.user, first_name=self.request.user.first_name,
                                                        last_name=self.request.user.last_name)
        return obj

    def get_context_data(self, **kwargs):
        # field that will be rendered using loop, so we don't have to render it manually
        self.extra_context['loop_fields'] = model_to_dict(self.get_object(),
                                                          exclude=('id', 'user', 'first_name', 'last_name'))

        # other field that will be rendered without using loop
        self.extra_context['profile'] = model_to_dict(self.get_object(), fields=('first_name', 'last_name',
                                                                                 'expertise', 'location', 'photo'))

        self.extra_context['menu_page'] = 'profile' # variable to indicate which page the user is in

        return super().get_context_data(**kwargs)

class ProfileEditView(UpdateView):
    """
    Views for User Profile Edit
    """
    template_name = 'portfolio/profile_edit.html'
    extra_context = dict()
    form_class = ProfileForm
    success_url = reverse_lazy('profile')

    def get_object(self, queryset=None):
        obj = self.form_class.Meta.model.objects.get(user=self.request.user)
        return obj

templates/portfolio/about.html
{% extends '_base.html' %}

{% block title %}About page{% endblock %}

{% block content %}
<h1>About page</h1>
{% endblock content %}

templates/portfolio/home.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Home page{% endblock title %}

{% block content %}
<h1>Home page</h1>
<img src="{% static 'images/falconx.png' %}" class="img-fluid" alt="FalconX launch"/>
{% endblock content %}

templates/portfolio/profile.html
{% extends '_base.html' %}
{% load static leaflet_tags crispy_forms_tags %}

{% block title %}GIS Portfolio | My Profile {% endblock title %}

{% block content %}

<div class="container">
    {#  Div for Profile Name #}
    <div class="row">
        <div class="col-md-10">
            <h1>{{ profile.first_name }} {{ profile.last_name }}</h1>
        </div>
    </div>

    <div class="row">

        {#  Side bar #}
        <div class="col-md-3">
            {#  Profile Photo #}
            <div class="text-center">
                {% if profile.photo %}
                    <img src="{{ profile.photo.url }}" class="avatar img-circle img-thumbnail"
                         alt="avatar">
                {% else %}
                    <img src="{% static 'images/avatar.png' %}" class="avatar img-circle img-thumbnail"
                         alt="avatar">
                {% endif %}
            </div>

            <br>

            {#  Expertise #}
            <div class="card">
                <div class="card-header"><strong>Expertise</strong> <i class="fa fa-desktop fa-1x"></i></div>
                <div class="list-group list-group-flush">
                    {% for expertise in profile.expertise %}
                          <li class="list-group-item">{{ expertise.name|title }}</li>
                    {% endfor %}
                </div>
            </div>

            <br>
        </div>


        <div class="col-md-9">
            {# Bootstrap tab header. For adding more tab, add more <li> to code below #}
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item" >
                    <a class="nav-link active" id="profile-tab" data-toggle="tab" href="#profile" role="tab"
                       aria-controls="home" aria-selected="true">
                        Profile
                    </a>
                </li>
            </ul>

            {# Tab content #}
            <div class="tab-content" id="my-tab-content">
                {# Tab content for Profile.  For adding more tab content, add more div to code below  #}
                {# Do not forget to add associated tab header #}
                <div class="tab-pane fade show active" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                    <br>
                     <div class="card">
                        <div class="card-header" style="height: 3rem;">
                            <strong>
                                <h4>
                                    Personal Info
                                    <a class="btn btn-sm btn-primary" href="{% url 'profile_edit' %}">
                                        Edit
                                    </a>
                                </h4>
                            </strong>
                        </div>
                        <div class="card-body">
                            <div class="container-fluid">
                                <div class="row">
                                    <div class="table-responsive">
                                        <table class="table table-striped table-sm">
                                            <tr>
                                                <th style="width: 20%">Email</th>
                                                <td>{{ request.user.email }}</td>
                                            </tr>
                                            {% for item in loop_fields.items %}
                                                {% if not item.0 in 'location, expertise, photo' %}
                                                    <tr>
                                                        <th style="width: 20%">{{ item.0|title }}</th>
                                                        <td>{{ item.1 }}</td>
                                                    </tr>
                                                {% endif %}
                                            {% endfor %}
                                            <tr>
                                                <th colspan="2">Location</th>
                                            </tr>
                                            <tr>
                                                <td colspan="2">
                                                    {% leaflet_map "main" callback="main_map_init" %}
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

{% endblock content %}

{% block css %}
    {% leaflet_css %}

    <style>
        .leaflet-container {  /* all maps */
            height: 75vh;
        }

    </style>
{% endblock css %}

{% block javascript %}
    {% leaflet_js %}
    <script type="text/javascript">
        let holes = [];
        function main_map_init(map, options) {
            if('{{ profile.location }}' != 'None'){
                var latLng = [{{ profile.location.1 }}, {{ profile.location.0 }}];
                map.setView(latLng, 11);
                var point = L.marker(latLng).addTo(map);
            }
        }
    </script>
{% endblock javascript %}

templates/portfolio/profile_edit.html
{% extends '_base.html' %}
{% load static leaflet_tags crispy_forms_tags %}

{% block title %}GIS Portfolio | Edit Profile{% endblock title %}

{% block content %}

<div class="container">
  <div class="card">
    <div class="card-header">
        Edit Profile
    </div>
    <div class="card-body">
        {% if form.non_field_errors %}
            <ul>
              {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
              {% endfor %}
            </ul>
        {% endif %}
        {{ form.media }}
        {% crispy form %}
    </div>
  </div>
</div>

{% endblock content %}

{% block css %}
    {% leaflet_css %}
    <style>
        .leaflet-container {  /* all maps */
            height: 75vh;
        }

        #specialbigmap {
            height: 800px;
        }

    </style>
    <link rel="stylesheet" href="{% static 'css/select2.min.css' %}"/>
{% endblock css %}

{% block javascript %}

    <script src="{% static 'js/select2.min.js' %}"></script>
    <script type="text/javascript">
        $('#id_expertise').select2();
    </script>

{% endblock %}

templates/portfolio/profile_list.html
{% extends '_base.html' %}
{% load static leaflet_tags portfolio_tags %}

{% block title %}GIS Portfolio | Home{% endblock title %}

{% block content %}

<div class="container-fluid">
    {% leaflet_map "main" callback="main_map_init" %}
</div>

{% endblock content %}

{% block css %}
    {% leaflet_css %}
    <link rel="stylesheet" href="{% static 'css/MarkerCluster.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/MarkerCluster.Default.css' %}"/>
    <link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v1.0.1/leaflet.fullscreen.css' rel='stylesheet' />

    <style>
        .leaflet-container {  /* all maps */
            height: 85vh;
        }

    </style>
{% endblock css %}

{% block javascript %}
    {% leaflet_js %}
    <script src="{% static 'js/leaflet.markercluster.js' %}"></script>
    <script src="{% static 'js/leaflet.ajax.min.js' %}"></script>
    <script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v1.0.1/Leaflet.fullscreen.min.js'></script>
    <script type="text/javascript">
        function main_map_init(map, options) {
            // add fullscreencontrol to map
            map.options.fullscreenControl = true;
            map.addControl(new L.Control.Fullscreen());

            //Initialize Leaflet map for displaying all Profile.

            // Define marker cluster group, so the marker will be grouped as we zoomin/zoomout and
            // will not be cluttered.
            var markers = L.markerClusterGroup();

            // Loop through all Profile
            {% for profile in object_list %}

                // Add Profile to cluster group if location field is set
                if('{{ profile.location }}' != 'None') {
                    var latLng = [{{ profile.location.1 }}, {{ profile.location.0 }}];
                }
                else {
                    var latLng = [-11.769893, 4.282790];
                }
                // use Profile photo if exists, if not then use avatar image
                {% if profile.photo %}
                    var popup = '<img src="{{ profile.photo.url }}" width="210px">';
                {% else %}
                    var img = "{% static 'images/avatar.png' %}";
                    popup = '<img src="' + img + '" width="210px">';
                {% endif %}

                popup += '<br/><b>Name:</b>{{ profile.first_name }} {{ profile.last_name }}' +
                            '<br/><b>Expertise:</b> {{ profile.expertise.all|expertises_to_comma_separated_string }}' +
                            '<br><b>Email:</b> <a href="mailto:{{ profile.user.email }}">{{ profile.user.email }}</a>' +
                            '<br/><b>Phone:</b> {{ profile.phone }}' +
                            '<br/><b>Address:</b> {{ profile.address }}';
                var point = L.marker(latLng).bindPopup(popup,{maxWidth:220}).addTo(markers);
            {% endfor %}

            // Add cluster group to map
            map.addLayer(markers);
        }
    </script>
{% endblock javascript %}